# -*- coding: utf-8 -*-
"""EJERCICIO_2_5_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iSCxHfRG2yEp8FuG7gET5xo6WHW9G9jQ
"""

import numpy as np
import matplotlib.pyplot as plt

# Datos de profundidad (cm) y temperatura (°C)
x_points = np.array([1.0, 2.5, 4.0, 5.5])
y_points = np.array([85, 78, 69, 60])

# Función de interpolación de Lagrange
def lagrange_interpolation(x, x_points, y_points):
    n = len(x_points)
    result = 0
    for i in range(n):
        term = y_points[i]
        for j in range(n):
            if i != j:
                term *= (x - x_points[j]) / (x_points[i] - x_points[j])
        result += term
    return result

# a) Estimar la temperatura a una profundidad de 3.0 cm
x_eval = 3.0
y_eval = lagrange_interpolation(x_eval, x_points, y_points)
print(f"Temperatura estimada a una profundidad de {x_eval} cm: {y_eval:.2f} °C")

# b) Graficar la interpolación en el rango [1.0, 5.5]
x_values = np.linspace(1.0, 5.5, 200)
y_values = [lagrange_interpolation(x, x_points, y_points) for x in x_values]

# Gráfica
plt.figure(figsize=(6, 4))
plt.plot(x_values, y_values, label="Interpolación de Lagrange", color="blue")
plt.scatter(x_points, y_points, color="red", label="Datos experimentales")
plt.scatter(x_eval, y_eval, color="green", label=f"Estimación en x={x_eval}")
plt.xlabel("Profundidad (cm)")
plt.ylabel("Temperatura (°C)")
plt.title("Interpolación de Lagrange - Temperatura en un bloque de motor")
plt.legend()
plt.grid(True)
plt.savefig("interpolacion_temperatura_motor.png")
plt.show()