# -*- coding: utf-8 -*-
"""EJERCICIO_3_5_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iSCxHfRG2yEp8FuG7gET5xo6WHW9G9jQ
"""

import numpy as np
import matplotlib.pyplot as plt

# Nuevos puntos de interpolación según la imagen
x_points = np.array([2.0, 4.0, 6.0, 8.0])  # Altitud (km)
y_points = np.array([2500, 2300, 2150, 2050])  # Consumo (kg/h)

# Función de interpolación de Lagrange
def lagrange_interpolation(x, x_points, y_points):
    n = len(x_points)
    result = 0
    for i in range(n):
        term = y_points[i]
        for j in range(n):
            if i != j:
                term *= (x - x_points[j]) / (x_points[i] - x_points[j])
        result += term
    return result

# a) Estimación del consumo a 5 km de altitud
altitud_objetivo = 5.0
consumo_estimado = lagrange_interpolation(altitud_objetivo, x_points, y_points)
print(f"Consumo estimado a {altitud_objetivo} km de altitud: {consumo_estimado:.2f} kg/h")

# b) Gráfica de la interpolación
x_values = np.linspace(min(x_points), max(x_points), 100)
y_values = [lagrange_interpolation(x, x_points, y_points) for x in x_values]

plt.figure(figsize=(8,5))
plt.plot(x_values, y_values, label="Interpolación de Lagrange", color="blue")
plt.scatter(x_points, y_points, color="red", label="Datos originales")
plt.scatter([altitud_objetivo], [consumo_estimado], color="green", label=f"Estimación a {altitud_objetivo} km")
plt.xlabel("Altitud (km)")
plt.ylabel("Consumo (kg/h)")
plt.title("Interpolación de Lagrange - Consumo de Combustible")
plt.legend()
plt.grid(True)
plt.savefig("interpolacion_consumo_combustible.png")
plt.show()